#ifndef _BUFFER_SIZES_H_
#define _BUFFER_SIZES_H_

#define MESSAGE_BUFFER_SIZE 2500  
#define MESSAGE_LORA_RECEPTION_BUFFER_SIZE 512  
#define HASH_BASE_64_BUFFER_SIZE 100
#define DEVICE_IDENTIFIER_BUFFER_SIZE 100
#define URL_SERVER_BUFFER_SIZE 100
#define TIMESTAMP_BUFFER_SIZE 20
#define BAND_STRING_BUFFER_SIZE 20
#define STRING_TRACKER_EVENT_SIZE 20
#define RECEPTION_MN_BUFFER_SIZE 256
#define STRING_MOTION_SIZE 5

#define ACK_BUFFER_SIZE 60



#endif // _BUFFER_SIZES_H_