#ifndef _TRACKER_STATUS_H_
#define _TRACKER_STATUS_H_

typedef enum {
    TRACKER_STATUS_GNSS_OBTAIN,
    TRACKER_STATUS_GNSS_UNAVAILABLE,
    TRACKER_STATUS_NONE_LOCALIZATION_MEAN_AVAILABLE,
    TRACKER_STATUS_GNSS_OBTAIN_CONNECTED_TO_MOBILE_NETWORK, // GNSS OK MN OK
    TRACKER_STATUS_GNSS_UNAVAILABLE_CONNECTED_TO_MOBILE_NETWORK, // GNSS NOK MN OK
    TRACKER_STATUS_GNSS_OBTAIN_CONNECTION_TO_MOBILE_NETWORK_UNAVAILABLE_TRYING_LORA,  // GNSS OK MN NOK
    TRACKER_STATUS_GNSS_UNAVAILABLE_CONNECTION_TO_MOBILE_NETWORK_UNAVAILABLE_TRYING_LORA, // GNSS NOK MN NOK
    
    TRACKER_STATUS_GNSS_LOADED_MESSAGE,  // RELOADED TYPE MESSAGE WITH GNSS INFO
    TRACKER_STATUS_IMU_LOADED_MESSAGE,  // RELOADED TYPE MESSAGE WITH IMU INFO

    TRACKER_STATUS_GNSS_UNAVAILABLE_CONNECTION_TO_MOBILE_NETWORK_UNAVAILABLE_LORA_UNAVAILABLE_GATHERING_INERTIAL_INFO, // GNSS NOK MN NOK LORA NOK
  
    TRACKER_STATUS_GNSS_OBTAIN_CONNECTION_TO_MOBILE_NETWORK_UNAVAILABLE_LORA_UNAVAILABLE_SAVING_MESSAGE,  // GNSS OK MN NOK
    TRACKER_STATUS_GNSS_OBTAIN_CONNECTED_TO_MOBILE_NETWORK_SAVING_MESSAGE,
    TRACKER_STATUS_GNSS_UNAVAILABLE_CONNECTED_TO_MOBILE_NETWORK_SAVING_MESSAGE,
    TRACKER_STATUS_GNSS_UNAVAILABLE_CONNECTION_TO_MOBILE_NETWORK_UNAVAILABLE_LORA_UNAVAILABLE_GATHERED_INERTIAL_INFO_SAVING_MESSAGE,

    TRACKER_STATUS_PARSE_ERROR
} trackerStatus_t;

#endif // _TRACKER_STATUS_H_