#ifndef _TRACKER_STATUS_H_
#define _TRACKER_STATUS_H_

typedef enum {
    TRACKER_STATUS_GNSS_OBTAIN,
    TRACKER_STATUS_GNSS_UNAVAILABLE,
    TRACKER_STATUS_NONE_LOCALIZATION_MEAN_AVAILABLE,
    TRACKER_STATUS_GNSS_OBTAIN_CONNECTED_TO_MOBILE_NETWORK,
    TRACKER_STATUS_GNSS_UNAVAILABLE_CONNECTED_TO_MOBILE_NETWORK,
    TRACKER_STATUS_GNSS_OBTAIN_CONNECTED_TO_MOBILE_NETWORK_SAVING_MESSAGE,
    TRACKER_STATUS_GNSS_UNAVAILABLE_CONNECTED_TO_MOBILE_NETWORK_SAVING_MESSAGE
} trackerStatus_t;

#endif // _TRACKER_STATUS_H_