#ifndef _CELLULAR_CONNECTION_STATUS_H_
#define _CELLULAR_CONNECTION_STATUS_H_

typedef enum {
    CELLULAR_CONNECTION_STATUS_UNAVAIBLE,
    CELLULAR_CONNECTION_STATUS_DISCONNECTED,
    CELLULAR_CONNECTION_STATUS_MODULE_DISCONNECTED,
    CELLULAR_CONNECTION_STATUS_TRYING_TO_CONNECT,
    CELLULAR_CONNECTION_STATUS_POOR_SIGNAL,
    CELLULAR_CONNECTION_STATUS_UNAVAIBLE_TO_REGISTER,
    CELLULAR_CONNECTION_STATUS_UNAVAIBLE_TO_RETRIV_OPERATORS_INFO,
    CELLULAR_CONNECTION_STATUS_UNAVAIBLE_TO_RETRIV_DATETIME,
    CELLULAR_CONNECTION_STATUS_UNAVAIBLE_TO_ATTACH_TO_PACKET_SERVICE,
    CELLULAR_CONNECTION_STATUS_UNAVAIBLE_TO_SET_PDP_CONTEXT,
    CELLULAR_CONNECTION_STATUS_INVALID_SIM,
    CELLULAR_CONNECTION_STATUS_CONNECTED_TO_NETWORK,
} CellularConnectionStatus_t;

#endif // _CELLULAR_CONNECTION_STATUS_H_