#ifndef _CELLULAR_TRANSMISSION_STATUS_H_
#define  _CELLULAR_TRANSMISSION_STATUS_H_

typedef enum {
    CELLULAR_TRANSMISSION_STATUS_UNAVAIBLE,
    CELLULAR_TRANSMISSION_STATUS_TRYNING_TO_SEND,
    CELLULAR_TRANSMISSION_STATUS_FAIL_TO_ACTIVATE_PDP,
    CELLULAR_TRANSMISSION_STATUS_SEND_OK,
    CELLULAR_TRANSMISSION_STATUS_UNAVAIBLE_TO_SEND,
} CellularTransmissionStatus_t;

#endif // _CELLULAR_TRANSMISSION_STATUS_H_