#ifndef _CELLULAR_TRANSCEIVER_STATUS_H_
#define  _CELLULAR_TRANSCEIVER_STATUS_H_

typedef enum {
    CELLULAR_TRANSCEIVER_STATUS_UNAVAIBLE,
    CELLULAR_TRANSCEIVER_STATUS_TRYNING_TO_SEND,
    CELLULAR_TRANSCEIVER_STATUS_FAIL_TO_ACTIVATE_PDP,
    CELLULAR_TRANSCEIVER_STATUS_SEND_OK,
    CELLULAR_TRANSCEIVER_STATUS_UNAVAIBLE_TO_SEND,
    CELLULAR_TRANSCEIVER_STATUS_ERROR_NULL_POINTER,
} CellularTransceiverStatus_t;

#endif // _CELLULAR_TRANSCEIVER_STATUS_H_