
#ifndef _GNSS_STATE_H_
#define _GNSS_STATE_H_

typedef enum {
    GNSS_STATE_DISCONNECTED,
    GNSS_STATE_TRYING_TO_CONNECT,
    GNSS_STATE_CONNECTION_OBTAIN,
    GNSS_STATE_CONNECTION_UNAVAILABLE,
    GNSS_STATE_DISCONECTING,
    GNSS_STATE_ERROR_NULL_POINTER,
} GNSSState_t;

#endif // _GNSS_STATE_H_